var dataSingle = [{
	"name": "node_modules/jscomplexity/test/fixture/complex/jquery/jquery-2.0.3.js",
	"cplx": 1468,
	"func": 551,
	"loc": 4432
}, {
	"name": "node_modules/jscomplexity/test/fixture/complex/jquery/min/jquery-2.0.3.min.js",
	"cplx": 1195,
	"func": 551,
	"loc": 2825
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/esprima.js",
	"cplx": 580,
	"func": 125,
	"loc": 2604
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/esprima.js",
	"cplx": 577,
	"func": 151,
	"loc": 2501
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.compat.js",
	"cplx": 575,
	"func": 234,
	"loc": 2038
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.js",
	"cplx": 565,
	"func": 228,
	"loc": 1928
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/lodash.js",
	"cplx": 560,
	"func": 233,
	"loc": 1994
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/browser/bluebird.js",
	"cplx": 528,
	"func": 478,
	"loc": 3069
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.min.js",
	"cplx": 488,
	"func": 228,
	"loc": 1179
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.compat.min.js",
	"cplx": 486,
	"func": 233,
	"loc": 1235
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.js",
	"cplx": 383,
	"func": 192,
	"loc": 2527
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.amd.js",
	"cplx": 383,
	"func": 191,
	"loc": 2476
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.underscore.js",
	"cplx": 362,
	"func": 175,
	"loc": 1291
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/compress.js",
	"cplx": 352,
	"func": 158,
	"loc": 1329
}, {
	"name": "node_modules/jscomplexity/node_modules/lodash/dist/lodash.underscore.min.js",
	"cplx": 322,
	"func": 173,
	"loc": 826
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.min.js",
	"cplx": 304,
	"func": 191,
	"loc": 1795
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.amd.min.js",
	"cplx": 304,
	"func": 190,
	"loc": 1745
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/parse.js",
	"cplx": 252,
	"func": 97,
	"loc": 1057
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/browser.js",
	"cplx": 182,
	"func": 58,
	"loc": 688
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/output.js",
	"cplx": 162,
	"func": 163,
	"loc": 851
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js",
	"cplx": 139,
	"func": 28,
	"loc": 1154
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/parser.js",
	"cplx": 139,
	"func": 29,
	"loc": 1155
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/minimatch.js",
	"cplx": 135,
	"func": 34,
	"loc": 480
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/promise.js",
	"cplx": 132,
	"func": 110,
	"loc": 685
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/promise.js",
	"cplx": 132,
	"func": 110,
	"loc": 685
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/async/lib/async.js",
	"cplx": 108,
	"func": 180,
	"loc": 618
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/glob.js",
	"cplx": 107,
	"func": 33,
	"loc": 385
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/scope.js",
	"cplx": 96,
	"func": 47,
	"loc": 415
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js",
	"cplx": 92,
	"func": 60,
	"loc": 482
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/javascript-compiler.js",
	"cplx": 92,
	"func": 61,
	"loc": 483
}, {
	"name": "node_modules/jscomplexity/node_modules/commander/index.js",
	"cplx": 87,
	"func": 50,
	"loc": 354
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/index.js",
	"cplx": 82,
	"func": 46,
	"loc": 286
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/sync.js",
	"cplx": 76,
	"func": 15,
	"loc": 255
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/commander/index.js",
	"cplx": 74,
	"func": 43,
	"loc": 306
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js",
	"cplx": 67,
	"func": 33,
	"loc": 321
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/compiler.js",
	"cplx": 67,
	"func": 34,
	"loc": 322
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.runtime.js",
	"cplx": 66,
	"func": 46,
	"loc": 363
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.runtime.amd.js",
	"cplx": 66,
	"func": 45,
	"loc": 336
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/ast.js",
	"cplx": 63,
	"func": 95,
	"loc": 603
}, {
	"name": "node_modules/jscomplexity/node_modules/cli-table/lib/index.js",
	"cplx": 57,
	"func": 21,
	"loc": 165
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/test/runner.js",
	"cplx": 53,
	"func": 21,
	"loc": 328
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.runtime.min.js",
	"cplx": 52,
	"func": 46,
	"loc": 241
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/handlebars.runtime.amd.min.js",
	"cplx": 52,
	"func": 45,
	"loc": 215
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/utils.js",
	"cplx": 51,
	"func": 43,
	"loc": 222
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/util.js",
	"cplx": 48,
	"func": 12,
	"loc": 156
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-node.js",
	"cplx": 47,
	"func": 20,
	"loc": 211
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-generator.js",
	"cplx": 43,
	"func": 16,
	"loc": 189
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/source-map-consumer.js",
	"cplx": 43,
	"func": 17,
	"loc": 230
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/test/runner.js",
	"cplx": 38,
	"func": 17,
	"loc": 244
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/common.js",
	"cplx": 37,
	"func": 11,
	"loc": 126
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/reduce.js",
	"cplx": 37,
	"func": 8,
	"loc": 125
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/reduce.js",
	"cplx": 37,
	"func": 8,
	"loc": 125
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/promisify.js",
	"cplx": 36,
	"func": 21,
	"loc": 169
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/promisify.js",
	"cplx": 36,
	"func": 21,
	"loc": 169
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/node_modules/amdefine/amdefine.js",
	"cplx": 35,
	"func": 19,
	"loc": 159
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/mozilla-ast.js",
	"cplx": 35,
	"func": 17,
	"loc": 172
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/captured_trace.js",
	"cplx": 34,
	"func": 15,
	"loc": 135
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/captured_trace.js",
	"cplx": 34,
	"func": 15,
	"loc": 135
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/base.js",
	"cplx": 33,
	"func": 15,
	"loc": 143
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/base.js",
	"cplx": 33,
	"func": 16,
	"loc": 144
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/index.js",
	"cplx": 30,
	"func": 13,
	"loc": 115
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/check-types/src/check-types.js",
	"cplx": 29,
	"func": 29,
	"loc": 178
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/check-types/src/check-types.js",
	"cplx": 29,
	"func": 29,
	"loc": 178
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/check-types/src/check-types.js",
	"cplx": 29,
	"func": 29,
	"loc": 178
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/src/module.js",
	"cplx": 27,
	"func": 33,
	"loc": 190
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/promise_array.js",
	"cplx": 27,
	"func": 16,
	"loc": 127
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/promise_array.js",
	"cplx": 27,
	"func": 16,
	"loc": 127
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/matrix-utilities/matrix-utilities.min.js",
	"cplx": 26,
	"func": 9,
	"loc": 67
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/matrix-utilities/matrix-utilities.js",
	"cplx": 26,
	"func": 9,
	"loc": 88
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/check-types/src/check-types.min.js",
	"cplx": 25,
	"func": 29,
	"loc": 146
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/check-types/src/check-types.min.js",
	"cplx": 25,
	"func": 29,
	"loc": 146
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/check-types/src/check-types.min.js",
	"cplx": 25,
	"func": 29,
	"loc": 146
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/map.js",
	"cplx": 23,
	"func": 10,
	"loc": 94
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/map.js",
	"cplx": 23,
	"func": 10,
	"loc": 94
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/ast.js",
	"cplx": 22,
	"func": 15,
	"loc": 148
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/ast.js",
	"cplx": 22,
	"func": 16,
	"loc": 149
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/src/project.js",
	"cplx": 22,
	"func": 27,
	"loc": 137
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/util.js",
	"cplx": 22,
	"func": 26,
	"loc": 178
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/util.js",
	"cplx": 22,
	"func": 26,
	"loc": 178
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/runtime.js",
	"cplx": 21,
	"func": 12,
	"loc": 101
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/runtime.js",
	"cplx": 21,
	"func": 13,
	"loc": 102
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/thenables.js",
	"cplx": 18,
	"func": 8,
	"loc": 75
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/thenables.js",
	"cplx": 18,
	"func": 8,
	"loc": 75
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/transform.js",
	"cplx": 15,
	"func": 33,
	"loc": 118
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/CallExpression.js",
	"cplx": 15,
	"func": 13,
	"loc": 50
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/promise_resolver.js",
	"cplx": 15,
	"func": 16,
	"loc": 90
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/join.js",
	"cplx": 15,
	"func": 7,
	"loc": 75
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/generators.js",
	"cplx": 15,
	"func": 12,
	"loc": 85
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/promise_resolver.js",
	"cplx": 15,
	"func": 16,
	"loc": 90
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/join.js",
	"cplx": 15,
	"func": 7,
	"loc": 75
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/generators.js",
	"cplx": 15,
	"func": 12,
	"loc": 85
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/tools/node.js",
	"cplx": 14,
	"func": 12,
	"loc": 97
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/build/mini-require.js",
	"cplx": 14,
	"func": 9,
	"loc": 69
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/test/compat.js",
	"cplx": 14,
	"func": 14,
	"loc": 134
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/test/compat.js",
	"cplx": 14,
	"func": 14,
	"loc": 132
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/using.js",
	"cplx": 14,
	"func": 23,
	"loc": 107
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/some.js",
	"cplx": 14,
	"func": 19,
	"loc": 83
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/progress.js",
	"cplx": 14,
	"func": 7,
	"loc": 63
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/finally.js",
	"cplx": 14,
	"func": 13,
	"loc": 56
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/errors.js",
	"cplx": 14,
	"func": 8,
	"loc": 95
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/using.js",
	"cplx": 14,
	"func": 23,
	"loc": 107
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/some.js",
	"cplx": 14,
	"func": 19,
	"loc": 83
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/progress.js",
	"cplx": 14,
	"func": 7,
	"loc": 63
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/finally.js",
	"cplx": 14,
	"func": 13,
	"loc": 56
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/errors.js",
	"cplx": 14,
	"func": 8,
	"loc": 95
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/node_modules/wordwrap/index.js",
	"cplx": 13,
	"func": 7,
	"loc": 47
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/printer.js",
	"cplx": 13,
	"func": 17,
	"loc": 99
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/printer.js",
	"cplx": 13,
	"func": 18,
	"loc": 100
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/custom/zalgo.js",
	"cplx": 12,
	"func": 5,
	"loc": 61
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/catch_filter.js",
	"cplx": 12,
	"func": 4,
	"loc": 55
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/call_get.js",
	"cplx": 12,
	"func": 11,
	"loc": 63
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/catch_filter.js",
	"cplx": 12,
	"func": 4,
	"loc": 55
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/call_get.js",
	"cplx": 12,
	"func": 11,
	"loc": 63
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/util.js",
	"cplx": 11,
	"func": 3,
	"loc": 91
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/utils.js",
	"cplx": 11,
	"func": 7,
	"loc": 51
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/utils.js",
	"cplx": 11,
	"func": 8,
	"loc": 52
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/system/supports-colors.js",
	"cplx": 11,
	"func": 1,
	"loc": 18
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/colors.js",
	"cplx": 9,
	"func": 20,
	"loc": 94
}, {
	"name": "node_modules/jscomplexity/node_modules/cli-table/lib/utils.js",
	"cplx": 9,
	"func": 6,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/props.js",
	"cplx": 9,
	"func": 10,
	"loc": 59
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/async.js",
	"cplx": 9,
	"func": 9,
	"loc": 59
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/assert.js",
	"cplx": 9,
	"func": 6,
	"loc": 50
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/props.js",
	"cplx": 9,
	"func": 10,
	"loc": 59
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/async.js",
	"cplx": 9,
	"func": 9,
	"loc": 59
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/assert.js",
	"cplx": 9,
	"func": 6,
	"loc": 50
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-source-map-consumer.js",
	"cplx": 8,
	"func": 42,
	"loc": 574
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/binary-search.js",
	"cplx": 8,
	"func": 3,
	"loc": 21
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/base64-vlq.js",
	"cplx": 8,
	"func": 5,
	"loc": 44
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/array-set.js",
	"cplx": 8,
	"func": 8,
	"loc": 34
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/index.js",
	"cplx": 8,
	"func": 2,
	"loc": 39
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/index.js",
	"cplx": 8,
	"func": 7,
	"loc": 41
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/timers.js",
	"cplx": 8,
	"func": 11,
	"loc": 61
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/nodeify.js",
	"cplx": 8,
	"func": 6,
	"loc": 33
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/timers.js",
	"cplx": 8,
	"func": 11,
	"loc": 61
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/nodeify.js",
	"cplx": 8,
	"func": 6,
	"loc": 33
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/build/assert-shim.js",
	"cplx": 7,
	"func": 8,
	"loc": 27
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inflight/test.js",
	"cplx": 7,
	"func": 15,
	"loc": 64
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/cancel.js",
	"cplx": 7,
	"func": 6,
	"loc": 39
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/cancel.js",
	"cplx": 7,
	"func": 6,
	"loc": 39
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-array-set.js",
	"cplx": 6,
	"func": 9,
	"loc": 72
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/mapping-list.js",
	"cplx": 6,
	"func": 6,
	"loc": 32
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/index.js",
	"cplx": 6,
	"func": 7,
	"loc": 38
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/race.js",
	"cplx": 6,
	"func": 6,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/queue.js",
	"cplx": 6,
	"func": 10,
	"loc": 65
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/race.js",
	"cplx": 6,
	"func": 6,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/queue.js",
	"cplx": 6,
	"func": 10,
	"loc": 65
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/node_modules/amdefine/intercept.js",
	"cplx": 5,
	"func": 2,
	"loc": 18
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/test/usage.js",
	"cplx": 5,
	"func": 31,
	"loc": 181
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/once/node_modules/wrappy/wrappy.js",
	"cplx": 5,
	"func": 4,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inflight/node_modules/wrappy/wrappy.js",
	"cplx": 5,
	"func": 4,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inflight/inflight.js",
	"cplx": 5,
	"func": 5,
	"loc": 32
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/test/run.js",
	"cplx": 5,
	"func": 3,
	"loc": 25
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/test/run.js",
	"cplx": 5,
	"func": 3,
	"loc": 25
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/maps/america.js",
	"cplx": 5,
	"func": 2,
	"loc": 13
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/extendStringPrototype.js",
	"cplx": 5,
	"func": 20,
	"loc": 61
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/synchronous_inspection.js",
	"cplx": 5,
	"func": 8,
	"loc": 26
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/schedule.js",
	"cplx": 5,
	"func": 5,
	"loc": 28
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/direct_resolve.js",
	"cplx": 5,
	"func": 8,
	"loc": 25
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/synchronous_inspection.js",
	"cplx": 5,
	"func": 8,
	"loc": 26
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/schedule.js",
	"cplx": 5,
	"func": 5,
	"loc": 28
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/direct_resolve.js",
	"cplx": 5,
	"func": 8,
	"loc": 25
}, {
	"name": "node_modules/jscomplexity/src/scan.js",
	"cplx": 4,
	"func": 8,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map/base64.js",
	"cplx": 4,
	"func": 4,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/exception.js",
	"cplx": 4,
	"func": 1,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/exception.js",
	"cplx": 4,
	"func": 2,
	"loc": 17
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/test/map.js",
	"cplx": 4,
	"func": 8,
	"loc": 28
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/index.js",
	"cplx": 4,
	"func": 2,
	"loc": 12
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/xml.js",
	"cplx": 4,
	"func": 17,
	"loc": 42
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/custom/trap.js",
	"cplx": 4,
	"func": 2,
	"loc": 40
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/settle.js",
	"cplx": 4,
	"func": 7,
	"loc": 30
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/settle.js",
	"cplx": 4,
	"func": 7,
	"loc": 30
}, {
	"name": "node_modules/jscomplexity/bin/lib/getSpec.js",
	"cplx": 4,
	"func": 1,
	"loc": 17
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-base64.js",
	"cplx": 3,
	"func": 7,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-base64-vlq.js",
	"cplx": 3,
	"func": 2,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/test/reflect.js",
	"cplx": 3,
	"func": 68,
	"loc": 465
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/src/safeName.js",
	"cplx": 3,
	"func": 1,
	"loc": 8
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/check-types/test/check-types.js",
	"cplx": 3,
	"func": 196,
	"loc": 487
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/SwitchCase.js",
	"cplx": 3,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/safeName.js",
	"cplx": 3,
	"func": 1,
	"loc": 8
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/src/index.js",
	"cplx": 3,
	"func": 2,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/check-types/test/check-types.js",
	"cplx": 3,
	"func": 196,
	"loc": 487
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/test/reflect.js",
	"cplx": 3,
	"func": 68,
	"loc": 465
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/check-types/test/check-types.js",
	"cplx": 3,
	"func": 196,
	"loc": 487
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/es5.js",
	"cplx": 3,
	"func": 6,
	"loc": 48
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/es5.js",
	"cplx": 3,
	"func": 6,
	"loc": 48
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-util.js",
	"cplx": 2,
	"func": 6,
	"loc": 161
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-source-node.js",
	"cplx": 2,
	"func": 31,
	"loc": 404
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-source-map-generator.js",
	"cplx": 2,
	"func": 35,
	"loc": 550
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-dog-fooding.js",
	"cplx": 2,
	"func": 2,
	"loc": 72
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-binary-search.js",
	"cplx": 2,
	"func": 8,
	"loc": 26
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/test/source-map/test-api.js",
	"cplx": 2,
	"func": 2,
	"loc": 13
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/Makefile.dryice.js",
	"cplx": 2,
	"func": 11,
	"loc": 70
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/lib/sourcemap.js",
	"cplx": 2,
	"func": 4,
	"loc": 34
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/node_modules/wordwrap/test/wrap.js",
	"cplx": 2,
	"func": 5,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/lib/index.js",
	"cplx": 2,
	"func": 1,
	"loc": 13
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js",
	"cplx": 2,
	"func": 1,
	"loc": 10
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/base.js",
	"cplx": 2,
	"func": 2,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/once/once.js",
	"cplx": 2,
	"func": 4,
	"loc": 15
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/once/node_modules/wrappy/test/basic.js",
	"cplx": 2,
	"func": 7,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/example/map.js",
	"cplx": 2,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inherits/inherits_browser.js",
	"cplx": 2,
	"func": 3,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inflight/node_modules/wrappy/test/basic.js",
	"cplx": 2,
	"func": 7,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/src/index.js",
	"cplx": 2,
	"func": 1,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/matrix-utilities/Gruntfile.js",
	"cplx": 2,
	"func": 2,
	"loc": 47
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/WhileStatement.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/UpdateExpression.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/UnaryExpression.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/NewExpression.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/MemberExpression.js",
	"cplx": 2,
	"func": 2,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/LogicalExpression.js",
	"cplx": 2,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/Literal.js",
	"cplx": 2,
	"func": 2,
	"loc": 9
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/IfStatement.js",
	"cplx": 2,
	"func": 3,
	"loc": 9
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ForStatement.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ForInStatement.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/DoWhileStatement.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/CatchClause.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/AssignmentExpression.js",
	"cplx": 2,
	"func": 3,
	"loc": 10
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/src/operators.js",
	"cplx": 2,
	"func": 2,
	"loc": 8
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/src/index.js",
	"cplx": 2,
	"func": 6,
	"loc": 30
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/Jakefile.js",
	"cplx": 2,
	"func": 6,
	"loc": 30
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/maps/zebra.js",
	"cplx": 2,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/maps/random.js",
	"cplx": 2,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/maps/rainbow.js",
	"cplx": 2,
	"func": 2,
	"loc": 9
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/errors_api_rejection.js",
	"cplx": 2,
	"func": 2,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/any.js",
	"cplx": 2,
	"func": 4,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/errors_api_rejection.js",
	"cplx": 2,
	"func": 2,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/any.js",
	"cplx": 2,
	"func": 4,
	"loc": 16
}, {
	"name": "node_modules/jscomplexity/bin/lib/outputHTMLReport.js",
	"cplx": 2,
	"func": 3,
	"loc": 19
}, {
	"name": "node_modules/jscomplexity/test/fixture/crash/no-crash.js",
	"cplx": 1,
	"func": 1,
	"loc": 1
}, {
	"name": "node_modules/jscomplexity/test/fixture/complex/empty.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/src/report.js",
	"cplx": 1,
	"func": 3,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/src/analyse.js",
	"cplx": 1,
	"func": 3,
	"loc": 22
}, {
	"name": "node_modules/jscomplexity/sample.js",
	"cplx": 1,
	"func": 1,
	"loc": 4
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/runtime.js",
	"cplx": 1,
	"func": 1,
	"loc": 1
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/typeof.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/switch.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/sequences.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/properties.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/loops.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/labels.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/issue-59.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/issue-44.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/issue-22.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/issue-143.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/issue-105.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/drop-unused.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/debugger.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/dead-code.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/conditionals.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/blocks.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/test/compress/arrays.js",
	"cplx": 1,
	"func": 1,
	"loc": 0
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/lib/source-map.js",
	"cplx": 1,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/build/test-suffix.js",
	"cplx": 1,
	"func": 1,
	"loc": 2
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/build/test-prefix.js",
	"cplx": 1,
	"func": 1,
	"loc": 1
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/uglify-js/node_modules/source-map/build/suffix-browser.js",
	"cplx": 1,
	"func": 1,
	"loc": 4
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/test/parse.js",
	"cplx": 1,
	"func": 34,
	"loc": 318
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/test/_.js",
	"cplx": 1,
	"func": 11,
	"loc": 39
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/node_modules/wordwrap/test/break.js",
	"cplx": 1,
	"func": 2,
	"loc": 19
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/node_modules/wordwrap/example/meat.js",
	"cplx": 1,
	"func": 1,
	"loc": 2
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/node_modules/wordwrap/example/center.js",
	"cplx": 1,
	"func": 1,
	"loc": 2
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/node_modules/optimist/example/usage-options.js",
	"cplx": 1,
	"func": 1,
	"loc": 13
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/safe-string.js",
	"cplx": 1,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars/compiler/visitor.js",
	"cplx": 1,
	"func": 2,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars.runtime.js",
	"cplx": 1,
	"func": 2,
	"loc": 19
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/cjs/handlebars.js",
	"cplx": 1,
	"func": 3,
	"loc": 25
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/safe-string.js",
	"cplx": 1,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars/compiler/visitor.js",
	"cplx": 1,
	"func": 3,
	"loc": 8
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars.runtime.js",
	"cplx": 1,
	"func": 3,
	"loc": 20
}, {
	"name": "node_modules/jscomplexity/node_modules/handlebars/dist/amd/handlebars.js",
	"cplx": 1,
	"func": 4,
	"loc": 26
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/test/balanced.js",
	"cplx": 1,
	"func": 1,
	"loc": 71
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/example.js",
	"cplx": 1,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/example.js",
	"cplx": 1,
	"func": 1,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inherits/test.js",
	"cplx": 1,
	"func": 3,
	"loc": 17
}, {
	"name": "node_modules/jscomplexity/node_modules/glob/node_modules/inherits/inherits.js",
	"cplx": 1,
	"func": 1,
	"loc": 1
}, {
	"name": "node_modules/jscomplexity/node_modules/esprima/test/test.js",
	"cplx": 1,
	"func": 1,
	"loc": 27815
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/test/project.js",
	"cplx": 1,
	"func": 71,
	"loc": 262
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/test/module.js",
	"cplx": 1,
	"func": 680,
	"loc": 1600
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex/node_modules/matrix-utilities/test/test.js",
	"cplx": 1,
	"func": 9,
	"loc": 81
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/WithStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/VariableDeclarator.js",
	"cplx": 1,
	"func": 3,
	"loc": 10
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/VariableDeclaration.js",
	"cplx": 1,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/TryStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ThrowStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ThisExpression.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/SwitchStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/SequenceExpression.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ReturnStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/Property.js",
	"cplx": 1,
	"func": 2,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ObjectExpression.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/Identifier.js",
	"cplx": 1,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/FunctionExpression.js",
	"cplx": 1,
	"func": 2,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/FunctionDeclaration.js",
	"cplx": 1,
	"func": 2,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ExpressionStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ContinueStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ConditionalExpression.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/BreakStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/BlockStatement.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/BinaryExpression.js",
	"cplx": 1,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/src/syntax/ArrayExpression.js",
	"cplx": 1,
	"func": 1,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/test/operators.js",
	"cplx": 1,
	"func": 33,
	"loc": 71
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/test/operands.js",
	"cplx": 1,
	"func": 28,
	"loc": 58
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/test/index.js",
	"cplx": 1,
	"func": 47,
	"loc": 138
}, {
	"name": "node_modules/jscomplexity/node_modules/escomplex-ast-moz/node_modules/escomplex-traits/src/operands.js",
	"cplx": 1,
	"func": 2,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/plain.js",
	"cplx": 1,
	"func": 7,
	"loc": 17
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/modules.js",
	"cplx": 1,
	"func": 2,
	"loc": 5
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/minimal.js",
	"cplx": 1,
	"func": 6,
	"loc": 14
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/markdown.js",
	"cplx": 1,
	"func": 7,
	"loc": 17
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/src/formats/json.js",
	"cplx": 1,
	"func": 1,
	"loc": 4
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/test/index.js",
	"cplx": 1,
	"func": 43,
	"loc": 137
}, {
	"name": "node_modules/jscomplexity/node_modules/complexity-report/node_modules/escomplex-js/node_modules/esprima/test/test.js",
	"cplx": 1,
	"func": 1,
	"loc": 23144
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/themes/generic-logging.js",
	"cplx": 1,
	"func": 1,
	"loc": 11
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/tests/safe-test.js",
	"cplx": 1,
	"func": 3,
	"loc": 33
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/tests/basic-test.js",
	"cplx": 1,
	"func": 3,
	"loc": 36
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/safe.js",
	"cplx": 1,
	"func": 1,
	"loc": 2
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/styles.js",
	"cplx": 1,
	"func": 1,
	"loc": 42
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/lib/index.js",
	"cplx": 1,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/examples/safe-string.js",
	"cplx": 1,
	"func": 1,
	"loc": 33
}, {
	"name": "node_modules/jscomplexity/node_modules/colors/examples/normal-usage.js",
	"cplx": 1,
	"func": 1,
	"loc": 35
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/filter.js",
	"cplx": 1,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/each.js",
	"cplx": 1,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/zalgo/bluebird.js",
	"cplx": 1,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/filter.js",
	"cplx": 1,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/each.js",
	"cplx": 1,
	"func": 3,
	"loc": 7
}, {
	"name": "node_modules/jscomplexity/node_modules/bluebird/js/main/bluebird.js",
	"cplx": 1,
	"func": 1,
	"loc": 3
}, {
	"name": "node_modules/jscomplexity/index.js",
	"cplx": 1,
	"func": 1,
	"loc": 4
}, {
	"name": "node_modules/jscomplexity/Gruntfile.js",
	"cplx": 1,
	"func": 1,
	"loc": 6
}, {
	"name": "node_modules/jscomplexity/bin/lib/outputCLIReport.js",
	"cplx": 1,
	"func": 2,
	"loc": 12
}]