var data = [{
	"name": "node_modules/escomplex/node_modules/check-types/src/check-types.js",
	"cplx": 42,
	"func": 85,
	"loc": 392
}, {
	"name": "node_modules/escomplex/node_modules/check-types/src/check-types.min.js",
	"cplx": 41,
	"func": 85,
	"loc": 320
}, {
	"name": "node_modules/escomplex/src/project.js",
	"cplx": 33,
	"func": 31,
	"loc": 180
}, {
	"name": "node_modules/escomplex/src/module.js",
	"cplx": 26,
	"func": 35,
	"loc": 192
}, {
	"name": "node_modules/escomplex/node_modules/matrix-utilities/matrix-utilities.min.js",
	"cplx": 26,
	"func": 9,
	"loc": 67
}, {
	"name": "node_modules/escomplex/node_modules/matrix-utilities/matrix-utilities.js",
	"cplx": 26,
	"func": 9,
	"loc": 88
}, {
	"name": "node_modules/escomplex/node_modules/check-types/test/check-types.js",
	"cplx": 15,
	"func": 512,
	"loc": 1286
}, {
	"name": "node_modules/escomplex/src/safeName.js",
	"cplx": 3,
	"func": 1,
	"loc": 8
}, {
	"name": "node_modules/escomplex/src/index.js",
	"cplx": 2,
	"func": 2,
	"loc": 12
}, {
	"name": "node_modules/escomplex/node_modules/matrix-utilities/Gruntfile.js",
	"cplx": 2,
	"func": 2,
	"loc": 47
}, {
	"name": "node_modules/escomplex/test/project.js",
	"cplx": 1,
	"func": 91,
	"loc": 326
}, {
	"name": "node_modules/escomplex/test/module.js",
	"cplx": 1,
	"func": 690,
	"loc": 1618
}, {
	"name": "node_modules/escomplex/node_modules/matrix-utilities/test/test.js",
	"cplx": 1,
	"func": 9,
	"loc": 81
}]