var dataMulti = {
	"path": "./node_modules/jscomplexity/node_modules",
	"name": "node_modules",
	"children": [{
		"path": "node_modules\\jscomplexity\\node_modules\\bluebird",
		"name": "bluebird",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js",
			"name": "js",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\browser",
				"name": "browser",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\browser\\bluebird.js",
					"name": "bluebird.js",
					"cplx": 528,
					"func": 478,
					"loc": 3069
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main",
				"name": "main",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\any.js",
					"name": "any.js",
					"cplx": 2,
					"func": 4,
					"loc": 16
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\assert.js",
					"name": "assert.js",
					"cplx": 9,
					"func": 6,
					"loc": 50
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\async.js",
					"name": "async.js",
					"cplx": 9,
					"func": 9,
					"loc": 59
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\bluebird.js",
					"name": "bluebird.js",
					"cplx": 1,
					"func": 1,
					"loc": 3
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\call_get.js",
					"name": "call_get.js",
					"cplx": 12,
					"func": 11,
					"loc": 63
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\cancel.js",
					"name": "cancel.js",
					"cplx": 7,
					"func": 6,
					"loc": 39
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\captured_trace.js",
					"name": "captured_trace.js",
					"cplx": 34,
					"func": 15,
					"loc": 135
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\catch_filter.js",
					"name": "catch_filter.js",
					"cplx": 12,
					"func": 4,
					"loc": 55
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\direct_resolve.js",
					"name": "direct_resolve.js",
					"cplx": 5,
					"func": 8,
					"loc": 25
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\each.js",
					"name": "each.js",
					"cplx": 1,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\errors.js",
					"name": "errors.js",
					"cplx": 14,
					"func": 8,
					"loc": 95
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\errors_api_rejection.js",
					"name": "errors_api_rejection.js",
					"cplx": 2,
					"func": 2,
					"loc": 11
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\es5.js",
					"name": "es5.js",
					"cplx": 3,
					"func": 6,
					"loc": 48
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\filter.js",
					"name": "filter.js",
					"cplx": 1,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\finally.js",
					"name": "finally.js",
					"cplx": 14,
					"func": 13,
					"loc": 56
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\generators.js",
					"name": "generators.js",
					"cplx": 15,
					"func": 12,
					"loc": 85
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\join.js",
					"name": "join.js",
					"cplx": 15,
					"func": 7,
					"loc": 75
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\map.js",
					"name": "map.js",
					"cplx": 23,
					"func": 10,
					"loc": 94
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\nodeify.js",
					"name": "nodeify.js",
					"cplx": 8,
					"func": 6,
					"loc": 33
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\progress.js",
					"name": "progress.js",
					"cplx": 14,
					"func": 7,
					"loc": 63
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\promise.js",
					"name": "promise.js",
					"cplx": 132,
					"func": 110,
					"loc": 685
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\promise_array.js",
					"name": "promise_array.js",
					"cplx": 27,
					"func": 16,
					"loc": 127
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\promise_resolver.js",
					"name": "promise_resolver.js",
					"cplx": 15,
					"func": 16,
					"loc": 90
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\promisify.js",
					"name": "promisify.js",
					"cplx": 36,
					"func": 21,
					"loc": 169
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\props.js",
					"name": "props.js",
					"cplx": 9,
					"func": 10,
					"loc": 59
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\queue.js",
					"name": "queue.js",
					"cplx": 6,
					"func": 10,
					"loc": 65
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\race.js",
					"name": "race.js",
					"cplx": 6,
					"func": 6,
					"loc": 35
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\reduce.js",
					"name": "reduce.js",
					"cplx": 37,
					"func": 8,
					"loc": 125
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\schedule.js",
					"name": "schedule.js",
					"cplx": 5,
					"func": 5,
					"loc": 28
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\settle.js",
					"name": "settle.js",
					"cplx": 4,
					"func": 7,
					"loc": 30
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\some.js",
					"name": "some.js",
					"cplx": 14,
					"func": 19,
					"loc": 83
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\synchronous_inspection.js",
					"name": "synchronous_inspection.js",
					"cplx": 5,
					"func": 8,
					"loc": 26
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\thenables.js",
					"name": "thenables.js",
					"cplx": 18,
					"func": 8,
					"loc": 75
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\timers.js",
					"name": "timers.js",
					"cplx": 8,
					"func": 11,
					"loc": 61
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\using.js",
					"name": "using.js",
					"cplx": 14,
					"func": 23,
					"loc": 107
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\main\\util.js",
					"name": "util.js",
					"cplx": 22,
					"func": 26,
					"loc": 178
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo",
				"name": "zalgo",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\any.js",
					"name": "any.js",
					"cplx": 2,
					"func": 4,
					"loc": 16
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\assert.js",
					"name": "assert.js",
					"cplx": 9,
					"func": 6,
					"loc": 50
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\async.js",
					"name": "async.js",
					"cplx": 9,
					"func": 9,
					"loc": 59
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\bluebird.js",
					"name": "bluebird.js",
					"cplx": 1,
					"func": 1,
					"loc": 3
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\call_get.js",
					"name": "call_get.js",
					"cplx": 12,
					"func": 11,
					"loc": 63
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\cancel.js",
					"name": "cancel.js",
					"cplx": 7,
					"func": 6,
					"loc": 39
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\captured_trace.js",
					"name": "captured_trace.js",
					"cplx": 34,
					"func": 15,
					"loc": 135
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\catch_filter.js",
					"name": "catch_filter.js",
					"cplx": 12,
					"func": 4,
					"loc": 55
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\direct_resolve.js",
					"name": "direct_resolve.js",
					"cplx": 5,
					"func": 8,
					"loc": 25
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\each.js",
					"name": "each.js",
					"cplx": 1,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\errors.js",
					"name": "errors.js",
					"cplx": 14,
					"func": 8,
					"loc": 95
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\errors_api_rejection.js",
					"name": "errors_api_rejection.js",
					"cplx": 2,
					"func": 2,
					"loc": 11
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\es5.js",
					"name": "es5.js",
					"cplx": 3,
					"func": 6,
					"loc": 48
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\filter.js",
					"name": "filter.js",
					"cplx": 1,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\finally.js",
					"name": "finally.js",
					"cplx": 14,
					"func": 13,
					"loc": 56
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\generators.js",
					"name": "generators.js",
					"cplx": 15,
					"func": 12,
					"loc": 85
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\join.js",
					"name": "join.js",
					"cplx": 15,
					"func": 7,
					"loc": 75
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\map.js",
					"name": "map.js",
					"cplx": 23,
					"func": 10,
					"loc": 94
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\nodeify.js",
					"name": "nodeify.js",
					"cplx": 8,
					"func": 6,
					"loc": 33
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\progress.js",
					"name": "progress.js",
					"cplx": 14,
					"func": 7,
					"loc": 63
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\promise.js",
					"name": "promise.js",
					"cplx": 132,
					"func": 110,
					"loc": 685
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\promise_array.js",
					"name": "promise_array.js",
					"cplx": 27,
					"func": 16,
					"loc": 127
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\promise_resolver.js",
					"name": "promise_resolver.js",
					"cplx": 15,
					"func": 16,
					"loc": 90
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\promisify.js",
					"name": "promisify.js",
					"cplx": 36,
					"func": 21,
					"loc": 169
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\props.js",
					"name": "props.js",
					"cplx": 9,
					"func": 10,
					"loc": 59
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\queue.js",
					"name": "queue.js",
					"cplx": 6,
					"func": 10,
					"loc": 65
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\race.js",
					"name": "race.js",
					"cplx": 6,
					"func": 6,
					"loc": 35
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\reduce.js",
					"name": "reduce.js",
					"cplx": 37,
					"func": 8,
					"loc": 125
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\schedule.js",
					"name": "schedule.js",
					"cplx": 5,
					"func": 5,
					"loc": 28
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\settle.js",
					"name": "settle.js",
					"cplx": 4,
					"func": 7,
					"loc": 30
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\some.js",
					"name": "some.js",
					"cplx": 14,
					"func": 19,
					"loc": 83
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\synchronous_inspection.js",
					"name": "synchronous_inspection.js",
					"cplx": 5,
					"func": 8,
					"loc": 26
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\thenables.js",
					"name": "thenables.js",
					"cplx": 18,
					"func": 8,
					"loc": 75
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\timers.js",
					"name": "timers.js",
					"cplx": 8,
					"func": 11,
					"loc": 61
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\using.js",
					"name": "using.js",
					"cplx": 14,
					"func": 23,
					"loc": 107
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\bluebird\\js\\zalgo\\util.js",
					"name": "util.js",
					"cplx": 22,
					"func": 26,
					"loc": 178
				}]
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\cli-table",
		"name": "cli-table",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\cli-table\\lib",
			"name": "lib",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\cli-table\\lib\\index.js",
				"name": "index.js",
				"cplx": 57,
				"func": 21,
				"loc": 165
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\cli-table\\lib\\utils.js",
				"name": "utils.js",
				"cplx": 9,
				"func": 6,
				"loc": 35
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\colors",
		"name": "colors",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\colors\\examples",
			"name": "examples",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\examples\\normal-usage.js",
				"name": "normal-usage.js",
				"cplx": 1,
				"func": 1,
				"loc": 35
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\examples\\safe-string.js",
				"name": "safe-string.js",
				"cplx": 1,
				"func": 1,
				"loc": 33
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib",
			"name": "lib",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\colors.js",
				"name": "colors.js",
				"cplx": 9,
				"func": 20,
				"loc": 94
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\custom",
				"name": "custom",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\custom\\trap.js",
					"name": "trap.js",
					"cplx": 4,
					"func": 2,
					"loc": 40
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\custom\\zalgo.js",
					"name": "zalgo.js",
					"cplx": 12,
					"func": 5,
					"loc": 61
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\extendStringPrototype.js",
				"name": "extendStringPrototype.js",
				"cplx": 5,
				"func": 20,
				"loc": 61
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\index.js",
				"name": "index.js",
				"cplx": 1,
				"func": 1,
				"loc": 3
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\maps",
				"name": "maps",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\maps\\america.js",
					"name": "america.js",
					"cplx": 5,
					"func": 2,
					"loc": 13
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\maps\\rainbow.js",
					"name": "rainbow.js",
					"cplx": 2,
					"func": 2,
					"loc": 9
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\maps\\random.js",
					"name": "random.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\maps\\zebra.js",
					"name": "zebra.js",
					"cplx": 2,
					"func": 1,
					"loc": 3
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\styles.js",
				"name": "styles.js",
				"cplx": 1,
				"func": 1,
				"loc": 42
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\system",
				"name": "system",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\colors\\lib\\system\\supports-colors.js",
					"name": "supports-colors.js",
					"cplx": 11,
					"func": 1,
					"loc": 18
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\colors\\safe.js",
			"name": "safe.js",
			"cplx": 1,
			"func": 1,
			"loc": 2
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\colors\\tests",
			"name": "tests",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\tests\\basic-test.js",
				"name": "basic-test.js",
				"cplx": 1,
				"func": 3,
				"loc": 36
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\tests\\safe-test.js",
				"name": "safe-test.js",
				"cplx": 1,
				"func": 3,
				"loc": 33
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\colors\\themes",
			"name": "themes",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\colors\\themes\\generic-logging.js",
				"name": "generic-logging.js",
				"cplx": 1,
				"func": 1,
				"loc": 11
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\commander",
		"name": "commander",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\commander\\index.js",
			"name": "index.js",
			"cplx": 87,
			"func": 50,
			"loc": 354
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\complexity-report",
		"name": "complexity-report",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\Jakefile.js",
			"name": "Jakefile.js",
			"cplx": 2,
			"func": 6,
			"loc": 30
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules",
			"name": "node_modules",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types",
				"name": "check-types",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types\\src",
					"name": "src",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types\\src\\check-types.js",
						"name": "check-types.js",
						"cplx": 29,
						"func": 29,
						"loc": 178
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types\\src\\check-types.min.js",
						"name": "check-types.min.js",
						"cplx": 25,
						"func": 29,
						"loc": 146
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\check-types\\test\\check-types.js",
						"name": "check-types.js",
						"cplx": 3,
						"func": 196,
						"loc": 487
					}]
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\commander",
				"name": "commander",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\commander\\index.js",
					"name": "index.js",
					"cplx": 74,
					"func": 43,
					"loc": 306
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js",
				"name": "escomplex-js",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima",
						"name": "esprima",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\bin",
							"name": "bin",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\bin\\esparse.js",
								"name": "esparse.js",
								"cplx": 0,
								"func": 1,
								"loc": 0
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\bin\\esvalidate.js",
								"name": "esvalidate.js",
								"cplx": 0,
								"func": 1,
								"loc": 0
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\esprima.js",
							"name": "esprima.js",
							"cplx": 580,
							"func": 125,
							"loc": 2604
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test",
							"name": "test",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test\\compat.js",
								"name": "compat.js",
								"cplx": 14,
								"func": 14,
								"loc": 132
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test\\reflect.js",
								"name": "reflect.js",
								"cplx": 3,
								"func": 68,
								"loc": 465
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test\\run.js",
								"name": "run.js",
								"cplx": 5,
								"func": 3,
								"loc": 25
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test\\runner.js",
								"name": "runner.js",
								"cplx": 38,
								"func": 17,
								"loc": 244
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\node_modules\\esprima\\test\\test.js",
								"name": "test.js",
								"cplx": 1,
								"func": 1,
								"loc": 23144
							}]
						}]
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\src",
					"name": "src",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\src\\index.js",
						"name": "index.js",
						"cplx": 2,
						"func": 6,
						"loc": 30
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\node_modules\\escomplex-js\\test\\index.js",
						"name": "index.js",
						"cplx": 1,
						"func": 43,
						"loc": 137
					}]
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src",
			"name": "src",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats",
				"name": "formats",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\json.js",
					"name": "json.js",
					"cplx": 1,
					"func": 1,
					"loc": 4
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\markdown.js",
					"name": "markdown.js",
					"cplx": 1,
					"func": 7,
					"loc": 17
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\minimal.js",
					"name": "minimal.js",
					"cplx": 1,
					"func": 6,
					"loc": 14
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\modules.js",
					"name": "modules.js",
					"cplx": 1,
					"func": 2,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\plain.js",
					"name": "plain.js",
					"cplx": 1,
					"func": 7,
					"loc": 17
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\formats\\xml.js",
					"name": "xml.js",
					"cplx": 4,
					"func": 17,
					"loc": 42
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\complexity-report\\src\\index.js",
				"name": "index.js",
				"cplx": 0,
				"func": 1,
				"loc": 0
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\escomplex",
		"name": "escomplex",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules",
			"name": "node_modules",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types",
				"name": "check-types",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types\\src",
					"name": "src",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types\\src\\check-types.js",
						"name": "check-types.js",
						"cplx": 29,
						"func": 29,
						"loc": 178
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types\\src\\check-types.min.js",
						"name": "check-types.min.js",
						"cplx": 25,
						"func": 29,
						"loc": 146
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\check-types\\test\\check-types.js",
						"name": "check-types.js",
						"cplx": 3,
						"func": 196,
						"loc": 487
					}]
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities",
				"name": "matrix-utilities",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities\\Gruntfile.js",
					"name": "Gruntfile.js",
					"cplx": 2,
					"func": 2,
					"loc": 47
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities\\matrix-utilities.js",
					"name": "matrix-utilities.js",
					"cplx": 26,
					"func": 9,
					"loc": 88
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities\\matrix-utilities.min.js",
					"name": "matrix-utilities.min.js",
					"cplx": 26,
					"func": 9,
					"loc": 67
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\node_modules\\matrix-utilities\\test\\test.js",
						"name": "test.js",
						"cplx": 1,
						"func": 9,
						"loc": 81
					}]
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\src",
			"name": "src",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\src\\index.js",
				"name": "index.js",
				"cplx": 2,
				"func": 1,
				"loc": 7
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\src\\module.js",
				"name": "module.js",
				"cplx": 27,
				"func": 33,
				"loc": 190
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\src\\project.js",
				"name": "project.js",
				"cplx": 22,
				"func": 27,
				"loc": 137
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\src\\safeName.js",
				"name": "safeName.js",
				"cplx": 3,
				"func": 1,
				"loc": 8
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\test",
			"name": "test",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\test\\module.js",
				"name": "module.js",
				"cplx": 1,
				"func": 680,
				"loc": 1600
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex\\test\\project.js",
				"name": "project.js",
				"cplx": 1,
				"func": 71,
				"loc": 262
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz",
		"name": "escomplex-ast-moz",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules",
			"name": "node_modules",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types",
				"name": "check-types",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types\\src",
					"name": "src",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types\\src\\check-types.js",
						"name": "check-types.js",
						"cplx": 29,
						"func": 29,
						"loc": 178
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types\\src\\check-types.min.js",
						"name": "check-types.min.js",
						"cplx": 25,
						"func": 29,
						"loc": 146
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\check-types\\test\\check-types.js",
						"name": "check-types.js",
						"cplx": 3,
						"func": 196,
						"loc": 487
					}]
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits",
				"name": "escomplex-traits",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\src",
					"name": "src",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\src\\index.js",
						"name": "index.js",
						"cplx": 3,
						"func": 2,
						"loc": 20
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\src\\operands.js",
						"name": "operands.js",
						"cplx": 1,
						"func": 2,
						"loc": 6
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\src\\operators.js",
						"name": "operators.js",
						"cplx": 2,
						"func": 2,
						"loc": 8
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\test\\index.js",
						"name": "index.js",
						"cplx": 1,
						"func": 47,
						"loc": 138
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\test\\operands.js",
						"name": "operands.js",
						"cplx": 1,
						"func": 28,
						"loc": 58
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\node_modules\\escomplex-traits\\test\\operators.js",
						"name": "operators.js",
						"cplx": 1,
						"func": 33,
						"loc": 71
					}]
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src",
			"name": "src",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\index.js",
				"name": "index.js",
				"cplx": 8,
				"func": 7,
				"loc": 41
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\safeName.js",
				"name": "safeName.js",
				"cplx": 3,
				"func": 1,
				"loc": 8
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax",
				"name": "syntax",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ArrayExpression.js",
					"name": "ArrayExpression.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\AssignmentExpression.js",
					"name": "AssignmentExpression.js",
					"cplx": 2,
					"func": 3,
					"loc": 10
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\BinaryExpression.js",
					"name": "BinaryExpression.js",
					"cplx": 1,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\BlockStatement.js",
					"name": "BlockStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\BreakStatement.js",
					"name": "BreakStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\CallExpression.js",
					"name": "CallExpression.js",
					"cplx": 15,
					"func": 13,
					"loc": 50
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\CatchClause.js",
					"name": "CatchClause.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ConditionalExpression.js",
					"name": "ConditionalExpression.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ContinueStatement.js",
					"name": "ContinueStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\DoWhileStatement.js",
					"name": "DoWhileStatement.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ExpressionStatement.js",
					"name": "ExpressionStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ForInStatement.js",
					"name": "ForInStatement.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ForStatement.js",
					"name": "ForStatement.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\FunctionDeclaration.js",
					"name": "FunctionDeclaration.js",
					"cplx": 1,
					"func": 2,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\FunctionExpression.js",
					"name": "FunctionExpression.js",
					"cplx": 1,
					"func": 2,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\Identifier.js",
					"name": "Identifier.js",
					"cplx": 1,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\IfStatement.js",
					"name": "IfStatement.js",
					"cplx": 2,
					"func": 3,
					"loc": 9
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\index.js",
					"name": "index.js",
					"cplx": 6,
					"func": 7,
					"loc": 38
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\Literal.js",
					"name": "Literal.js",
					"cplx": 2,
					"func": 2,
					"loc": 9
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\LogicalExpression.js",
					"name": "LogicalExpression.js",
					"cplx": 2,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\MemberExpression.js",
					"name": "MemberExpression.js",
					"cplx": 2,
					"func": 2,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\NewExpression.js",
					"name": "NewExpression.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ObjectExpression.js",
					"name": "ObjectExpression.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\Property.js",
					"name": "Property.js",
					"cplx": 1,
					"func": 2,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ReturnStatement.js",
					"name": "ReturnStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\SequenceExpression.js",
					"name": "SequenceExpression.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\SwitchCase.js",
					"name": "SwitchCase.js",
					"cplx": 3,
					"func": 3,
					"loc": 7
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\SwitchStatement.js",
					"name": "SwitchStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ThisExpression.js",
					"name": "ThisExpression.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\ThrowStatement.js",
					"name": "ThrowStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\TryStatement.js",
					"name": "TryStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\UnaryExpression.js",
					"name": "UnaryExpression.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\UpdateExpression.js",
					"name": "UpdateExpression.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\VariableDeclaration.js",
					"name": "VariableDeclaration.js",
					"cplx": 1,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\VariableDeclarator.js",
					"name": "VariableDeclarator.js",
					"cplx": 1,
					"func": 3,
					"loc": 10
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\WhileStatement.js",
					"name": "WhileStatement.js",
					"cplx": 2,
					"func": 2,
					"loc": 6
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\escomplex-ast-moz\\src\\syntax\\WithStatement.js",
					"name": "WithStatement.js",
					"cplx": 1,
					"func": 1,
					"loc": 5
				}]
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\esprima",
		"name": "esprima",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\esprima\\bin",
			"name": "bin",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\bin\\esparse.js",
				"name": "esparse.js",
				"cplx": 0,
				"func": 1,
				"loc": 0
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\bin\\esvalidate.js",
				"name": "esvalidate.js",
				"cplx": 0,
				"func": 1,
				"loc": 0
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\esprima\\esprima.js",
			"name": "esprima.js",
			"cplx": 577,
			"func": 151,
			"loc": 2501
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test",
			"name": "test",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test\\compat.js",
				"name": "compat.js",
				"cplx": 14,
				"func": 14,
				"loc": 134
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test\\reflect.js",
				"name": "reflect.js",
				"cplx": 3,
				"func": 68,
				"loc": 465
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test\\run.js",
				"name": "run.js",
				"cplx": 5,
				"func": 3,
				"loc": 25
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test\\runner.js",
				"name": "runner.js",
				"cplx": 53,
				"func": 21,
				"loc": 328
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\esprima\\test\\test.js",
				"name": "test.js",
				"cplx": 1,
				"func": 1,
				"loc": 27815
			}]
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\glob",
		"name": "glob",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\glob\\common.js",
			"name": "common.js",
			"cplx": 37,
			"func": 11,
			"loc": 126
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\glob\\glob.js",
			"name": "glob.js",
			"cplx": 107,
			"func": 33,
			"loc": 385
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules",
			"name": "node_modules",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight",
				"name": "inflight",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\inflight.js",
					"name": "inflight.js",
					"cplx": 5,
					"func": 5,
					"loc": 32
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\node_modules\\wrappy",
						"name": "wrappy",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\node_modules\\wrappy\\test",
							"name": "test",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\node_modules\\wrappy\\test\\basic.js",
								"name": "basic.js",
								"cplx": 2,
								"func": 7,
								"loc": 35
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\node_modules\\wrappy\\wrappy.js",
							"name": "wrappy.js",
							"cplx": 5,
							"func": 4,
							"loc": 20
						}]
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inflight\\test.js",
					"name": "test.js",
					"cplx": 7,
					"func": 15,
					"loc": 64
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inherits",
				"name": "inherits",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inherits\\inherits.js",
					"name": "inherits.js",
					"cplx": 1,
					"func": 1,
					"loc": 1
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inherits\\inherits_browser.js",
					"name": "inherits_browser.js",
					"cplx": 2,
					"func": 3,
					"loc": 16
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\inherits\\test.js",
					"name": "test.js",
					"cplx": 1,
					"func": 3,
					"loc": 17
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch",
				"name": "minimatch",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\browser.js",
					"name": "browser.js",
					"cplx": 182,
					"func": 58,
					"loc": 688
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\minimatch.js",
					"name": "minimatch.js",
					"cplx": 135,
					"func": 34,
					"loc": 480
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion",
						"name": "brace-expansion",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\example.js",
							"name": "example.js",
							"cplx": 1,
							"func": 1,
							"loc": 6
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\index.js",
							"name": "index.js",
							"cplx": 30,
							"func": 13,
							"loc": 115
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules",
							"name": "node_modules",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\balanced-match",
								"name": "balanced-match",
								"children": [{
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\balanced-match\\example.js",
									"name": "example.js",
									"cplx": 1,
									"func": 1,
									"loc": 3
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\balanced-match\\index.js",
									"name": "index.js",
									"cplx": 8,
									"func": 2,
									"loc": 39
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\balanced-match\\test",
									"name": "test",
									"children": [{
										"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\balanced-match\\test\\balanced.js",
										"name": "balanced.js",
										"cplx": 1,
										"func": 1,
										"loc": 71
									}]
								}]
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map",
								"name": "concat-map",
								"children": [{
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\example",
									"name": "example",
									"children": [{
										"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\example\\map.js",
										"name": "map.js",
										"cplx": 2,
										"func": 1,
										"loc": 5
									}]
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\index.js",
									"name": "index.js",
									"cplx": 4,
									"func": 2,
									"loc": 12
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\test",
									"name": "test",
									"children": [{
										"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\test\\map.js",
										"name": "map.js",
										"cplx": 4,
										"func": 8,
										"loc": 28
									}]
								}]
							}]
						}]
					}]
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once",
				"name": "once",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\node_modules\\wrappy",
						"name": "wrappy",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\node_modules\\wrappy\\test",
							"name": "test",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\node_modules\\wrappy\\test\\basic.js",
								"name": "basic.js",
								"cplx": 2,
								"func": 7,
								"loc": 35
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\node_modules\\wrappy\\wrappy.js",
							"name": "wrappy.js",
							"cplx": 5,
							"func": 4,
							"loc": 20
						}]
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\glob\\node_modules\\once\\once.js",
					"name": "once.js",
					"cplx": 2,
					"func": 4,
					"loc": 15
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\glob\\sync.js",
			"name": "sync.js",
			"cplx": 76,
			"func": 15,
			"loc": 255
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\handlebars",
		"name": "handlebars",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist",
			"name": "dist",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd",
				"name": "amd",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars",
					"name": "handlebars",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\base.js",
						"name": "base.js",
						"cplx": 33,
						"func": 16,
						"loc": 144
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler",
						"name": "compiler",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\ast.js",
							"name": "ast.js",
							"cplx": 22,
							"func": 16,
							"loc": 149
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\base.js",
							"name": "base.js",
							"cplx": 2,
							"func": 2,
							"loc": 11
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\compiler.js",
							"name": "compiler.js",
							"cplx": 67,
							"func": 34,
							"loc": 322
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\javascript-compiler.js",
							"name": "javascript-compiler.js",
							"cplx": 92,
							"func": 61,
							"loc": 483
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\parser.js",
							"name": "parser.js",
							"cplx": 139,
							"func": 29,
							"loc": 1155
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\printer.js",
							"name": "printer.js",
							"cplx": 13,
							"func": 18,
							"loc": 100
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\compiler\\visitor.js",
							"name": "visitor.js",
							"cplx": 1,
							"func": 3,
							"loc": 8
						}]
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\exception.js",
						"name": "exception.js",
						"cplx": 4,
						"func": 2,
						"loc": 17
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\runtime.js",
						"name": "runtime.js",
						"cplx": 21,
						"func": 13,
						"loc": 102
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\safe-string.js",
						"name": "safe-string.js",
						"cplx": 1,
						"func": 3,
						"loc": 7
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars\\utils.js",
						"name": "utils.js",
						"cplx": 11,
						"func": 8,
						"loc": 52
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars.js",
					"name": "handlebars.js",
					"cplx": 1,
					"func": 4,
					"loc": 26
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\amd\\handlebars.runtime.js",
					"name": "handlebars.runtime.js",
					"cplx": 1,
					"func": 3,
					"loc": 20
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs",
				"name": "cjs",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars",
					"name": "handlebars",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\base.js",
						"name": "base.js",
						"cplx": 33,
						"func": 15,
						"loc": 143
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler",
						"name": "compiler",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\ast.js",
							"name": "ast.js",
							"cplx": 22,
							"func": 15,
							"loc": 148
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\base.js",
							"name": "base.js",
							"cplx": 2,
							"func": 1,
							"loc": 10
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\compiler.js",
							"name": "compiler.js",
							"cplx": 67,
							"func": 33,
							"loc": 321
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\javascript-compiler.js",
							"name": "javascript-compiler.js",
							"cplx": 92,
							"func": 60,
							"loc": 482
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\parser.js",
							"name": "parser.js",
							"cplx": 139,
							"func": 28,
							"loc": 1154
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\printer.js",
							"name": "printer.js",
							"cplx": 13,
							"func": 17,
							"loc": 99
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\compiler\\visitor.js",
							"name": "visitor.js",
							"cplx": 1,
							"func": 2,
							"loc": 7
						}]
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\exception.js",
						"name": "exception.js",
						"cplx": 4,
						"func": 1,
						"loc": 16
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\runtime.js",
						"name": "runtime.js",
						"cplx": 21,
						"func": 12,
						"loc": 101
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\safe-string.js",
						"name": "safe-string.js",
						"cplx": 1,
						"func": 2,
						"loc": 6
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars\\utils.js",
						"name": "utils.js",
						"cplx": 11,
						"func": 7,
						"loc": 51
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars.js",
					"name": "handlebars.js",
					"cplx": 1,
					"func": 3,
					"loc": 25
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\cjs\\handlebars.runtime.js",
					"name": "handlebars.runtime.js",
					"cplx": 1,
					"func": 2,
					"loc": 19
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.amd.js",
				"name": "handlebars.amd.js",
				"cplx": 383,
				"func": 191,
				"loc": 2476
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.amd.min.js",
				"name": "handlebars.amd.min.js",
				"cplx": 304,
				"func": 190,
				"loc": 1745
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.js",
				"name": "handlebars.js",
				"cplx": 383,
				"func": 192,
				"loc": 2527
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.min.js",
				"name": "handlebars.min.js",
				"cplx": 304,
				"func": 191,
				"loc": 1795
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.runtime.amd.js",
				"name": "handlebars.runtime.amd.js",
				"cplx": 66,
				"func": 45,
				"loc": 336
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.runtime.amd.min.js",
				"name": "handlebars.runtime.amd.min.js",
				"cplx": 52,
				"func": 45,
				"loc": 215
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.runtime.js",
				"name": "handlebars.runtime.js",
				"cplx": 66,
				"func": 46,
				"loc": 363
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\dist\\handlebars.runtime.min.js",
				"name": "handlebars.runtime.min.js",
				"cplx": 52,
				"func": 46,
				"loc": 241
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib",
			"name": "lib",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars",
				"name": "handlebars",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\base.js",
					"name": "base.js",
					"cplx": 0,
					"func": 1,
					"loc": 0
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler",
					"name": "compiler",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\ast.js",
						"name": "ast.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\base.js",
						"name": "base.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\compiler.js",
						"name": "compiler.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\javascript-compiler.js",
						"name": "javascript-compiler.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\parser.js",
						"name": "parser.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\printer.js",
						"name": "printer.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\compiler\\visitor.js",
						"name": "visitor.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\exception.js",
					"name": "exception.js",
					"cplx": 0,
					"func": 1,
					"loc": 0
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\runtime.js",
					"name": "runtime.js",
					"cplx": 0,
					"func": 1,
					"loc": 0
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\safe-string.js",
					"name": "safe-string.js",
					"cplx": 0,
					"func": 1,
					"loc": 0
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars\\utils.js",
					"name": "utils.js",
					"cplx": 0,
					"func": 1,
					"loc": 0
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars.js",
				"name": "handlebars.js",
				"cplx": 0,
				"func": 1,
				"loc": 0
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\handlebars.runtime.js",
				"name": "handlebars.runtime.js",
				"cplx": 0,
				"func": 1,
				"loc": 0
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\lib\\index.js",
				"name": "index.js",
				"cplx": 2,
				"func": 1,
				"loc": 13
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules",
			"name": "node_modules",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist",
				"name": "optimist",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example",
					"name": "example",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\bool.js",
						"name": "bool.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\boolean_double.js",
						"name": "boolean_double.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\boolean_single.js",
						"name": "boolean_single.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\default_hash.js",
						"name": "default_hash.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\default_singles.js",
						"name": "default_singles.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\divide.js",
						"name": "divide.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\line_count.js",
						"name": "line_count.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\line_count_options.js",
						"name": "line_count_options.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\line_count_wrap.js",
						"name": "line_count_wrap.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\nonopt.js",
						"name": "nonopt.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\reflect.js",
						"name": "reflect.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\short.js",
						"name": "short.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\string.js",
						"name": "string.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\usage-options.js",
						"name": "usage-options.js",
						"cplx": 1,
						"func": 1,
						"loc": 13
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\example\\xup.js",
						"name": "xup.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\index.js",
					"name": "index.js",
					"cplx": 82,
					"func": 46,
					"loc": 286
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap",
						"name": "wordwrap",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\example",
							"name": "example",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\example\\center.js",
								"name": "center.js",
								"cplx": 1,
								"func": 1,
								"loc": 2
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\example\\meat.js",
								"name": "meat.js",
								"cplx": 1,
								"func": 1,
								"loc": 2
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\index.js",
							"name": "index.js",
							"cplx": 13,
							"func": 7,
							"loc": 47
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\test",
							"name": "test",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\test\\break.js",
								"name": "break.js",
								"cplx": 1,
								"func": 2,
								"loc": 19
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\node_modules\\wordwrap\\test\\wrap.js",
								"name": "wrap.js",
								"cplx": 2,
								"func": 5,
								"loc": 20
							}]
						}]
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\parse.js",
						"name": "parse.js",
						"cplx": 1,
						"func": 34,
						"loc": 318
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\usage.js",
						"name": "usage.js",
						"cplx": 5,
						"func": 31,
						"loc": 181
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\_",
						"name": "_",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\_\\argv.js",
							"name": "argv.js",
							"cplx": 0,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\_\\bin.js",
							"name": "bin.js",
							"cplx": 0,
							"func": 1,
							"loc": 0
						}]
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\optimist\\test\\_.js",
						"name": "_.js",
						"cplx": 1,
						"func": 11,
						"loc": 39
					}]
				}]
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js",
				"name": "uglify-js",
				"children": [{
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib",
					"name": "lib",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\ast.js",
						"name": "ast.js",
						"cplx": 63,
						"func": 95,
						"loc": 603
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\compress.js",
						"name": "compress.js",
						"cplx": 352,
						"func": 158,
						"loc": 1329
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\mozilla-ast.js",
						"name": "mozilla-ast.js",
						"cplx": 35,
						"func": 17,
						"loc": 172
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\output.js",
						"name": "output.js",
						"cplx": 162,
						"func": 163,
						"loc": 851
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\parse.js",
						"name": "parse.js",
						"cplx": 252,
						"func": 97,
						"loc": 1057
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\scope.js",
						"name": "scope.js",
						"cplx": 96,
						"func": 47,
						"loc": 415
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\sourcemap.js",
						"name": "sourcemap.js",
						"cplx": 2,
						"func": 4,
						"loc": 34
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\transform.js",
						"name": "transform.js",
						"cplx": 15,
						"func": 33,
						"loc": 118
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\lib\\utils.js",
						"name": "utils.js",
						"cplx": 51,
						"func": 43,
						"loc": 222
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules",
					"name": "node_modules",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\async",
						"name": "async",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\async\\lib",
							"name": "lib",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\async\\lib\\async.js",
								"name": "async.js",
								"cplx": 108,
								"func": 180,
								"loc": 618
							}]
						}]
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map",
						"name": "source-map",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build",
							"name": "build",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build\\assert-shim.js",
								"name": "assert-shim.js",
								"cplx": 7,
								"func": 8,
								"loc": 27
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build\\mini-require.js",
								"name": "mini-require.js",
								"cplx": 14,
								"func": 9,
								"loc": 69
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build\\suffix-browser.js",
								"name": "suffix-browser.js",
								"cplx": 1,
								"func": 1,
								"loc": 4
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build\\test-prefix.js",
								"name": "test-prefix.js",
								"cplx": 1,
								"func": 1,
								"loc": 1
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\build\\test-suffix.js",
								"name": "test-suffix.js",
								"cplx": 1,
								"func": 1,
								"loc": 2
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib",
							"name": "lib",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map",
								"name": "source-map",
								"children": [{
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\array-set.js",
									"name": "array-set.js",
									"cplx": 8,
									"func": 8,
									"loc": 34
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\base64-vlq.js",
									"name": "base64-vlq.js",
									"cplx": 8,
									"func": 5,
									"loc": 44
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\base64.js",
									"name": "base64.js",
									"cplx": 4,
									"func": 4,
									"loc": 16
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\binary-search.js",
									"name": "binary-search.js",
									"cplx": 8,
									"func": 3,
									"loc": 21
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\mapping-list.js",
									"name": "mapping-list.js",
									"cplx": 6,
									"func": 6,
									"loc": 32
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\source-map-consumer.js",
									"name": "source-map-consumer.js",
									"cplx": 43,
									"func": 17,
									"loc": 230
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\source-map-generator.js",
									"name": "source-map-generator.js",
									"cplx": 43,
									"func": 16,
									"loc": 189
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\source-node.js",
									"name": "source-node.js",
									"cplx": 47,
									"func": 20,
									"loc": 211
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map\\util.js",
									"name": "util.js",
									"cplx": 48,
									"func": 12,
									"loc": 156
								}]
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\lib\\source-map.js",
								"name": "source-map.js",
								"cplx": 1,
								"func": 1,
								"loc": 3
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\Makefile.dryice.js",
							"name": "Makefile.dryice.js",
							"cplx": 2,
							"func": 11,
							"loc": 70
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\node_modules",
							"name": "node_modules",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\node_modules\\amdefine",
								"name": "amdefine",
								"children": [{
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\node_modules\\amdefine\\amdefine.js",
									"name": "amdefine.js",
									"cplx": 35,
									"func": 19,
									"loc": 159
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\node_modules\\amdefine\\intercept.js",
									"name": "intercept.js",
									"cplx": 5,
									"func": 2,
									"loc": 18
								}]
							}]
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test",
							"name": "test",
							"children": [{
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\run-tests.js",
								"name": "run-tests.js",
								"cplx": 0,
								"func": 1,
								"loc": 0
							}, {
								"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map",
								"name": "source-map",
								"children": [{
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-api.js",
									"name": "test-api.js",
									"cplx": 2,
									"func": 2,
									"loc": 13
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-array-set.js",
									"name": "test-array-set.js",
									"cplx": 6,
									"func": 9,
									"loc": 72
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-base64-vlq.js",
									"name": "test-base64-vlq.js",
									"cplx": 3,
									"func": 2,
									"loc": 11
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-base64.js",
									"name": "test-base64.js",
									"cplx": 3,
									"func": 7,
									"loc": 16
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-binary-search.js",
									"name": "test-binary-search.js",
									"cplx": 2,
									"func": 8,
									"loc": 26
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-dog-fooding.js",
									"name": "test-dog-fooding.js",
									"cplx": 2,
									"func": 2,
									"loc": 72
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-source-map-consumer.js",
									"name": "test-source-map-consumer.js",
									"cplx": 8,
									"func": 42,
									"loc": 574
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-source-map-generator.js",
									"name": "test-source-map-generator.js",
									"cplx": 2,
									"func": 35,
									"loc": 550
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-source-node.js",
									"name": "test-source-node.js",
									"cplx": 2,
									"func": 31,
									"loc": 404
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\test-util.js",
									"name": "test-util.js",
									"cplx": 2,
									"func": 6,
									"loc": 161
								}, {
									"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\node_modules\\source-map\\test\\source-map\\util.js",
									"name": "util.js",
									"cplx": 11,
									"func": 3,
									"loc": 91
								}]
							}]
						}]
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test",
					"name": "test",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress",
						"name": "compress",
						"children": [{
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\arrays.js",
							"name": "arrays.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\blocks.js",
							"name": "blocks.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\conditionals.js",
							"name": "conditionals.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\dead-code.js",
							"name": "dead-code.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\debugger.js",
							"name": "debugger.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\drop-unused.js",
							"name": "drop-unused.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-105.js",
							"name": "issue-105.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-12.js",
							"name": "issue-12.js",
							"cplx": 0,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-143.js",
							"name": "issue-143.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-22.js",
							"name": "issue-22.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-44.js",
							"name": "issue-44.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\issue-59.js",
							"name": "issue-59.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\labels.js",
							"name": "labels.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\loops.js",
							"name": "loops.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\properties.js",
							"name": "properties.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\sequences.js",
							"name": "sequences.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\switch.js",
							"name": "switch.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}, {
							"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\compress\\typeof.js",
							"name": "typeof.js",
							"cplx": 1,
							"func": 1,
							"loc": 0
						}]
					}, {
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\test\\run-tests.js",
						"name": "run-tests.js",
						"cplx": 0,
						"func": 1,
						"loc": 0
					}]
				}, {
					"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\tools",
					"name": "tools",
					"children": [{
						"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\node_modules\\uglify-js\\tools\\node.js",
						"name": "node.js",
						"cplx": 14,
						"func": 12,
						"loc": 97
					}]
				}]
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\handlebars\\runtime.js",
			"name": "runtime.js",
			"cplx": 1,
			"func": 1,
			"loc": 1
		}]
	}, {
		"path": "node_modules\\jscomplexity\\node_modules\\lodash",
		"name": "lodash",
		"children": [{
			"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist",
			"name": "dist",
			"children": [{
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.compat.js",
				"name": "lodash.compat.js",
				"cplx": 575,
				"func": 234,
				"loc": 2038
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.compat.min.js",
				"name": "lodash.compat.min.js",
				"cplx": 486,
				"func": 233,
				"loc": 1235
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.js",
				"name": "lodash.js",
				"cplx": 565,
				"func": 228,
				"loc": 1928
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.min.js",
				"name": "lodash.min.js",
				"cplx": 488,
				"func": 228,
				"loc": 1179
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.underscore.js",
				"name": "lodash.underscore.js",
				"cplx": 362,
				"func": 175,
				"loc": 1291
			}, {
				"path": "node_modules\\jscomplexity\\node_modules\\lodash\\dist\\lodash.underscore.min.js",
				"name": "lodash.underscore.min.js",
				"cplx": 322,
				"func": 173,
				"loc": 826
			}]
		}, {
			"path": "node_modules\\jscomplexity\\node_modules\\lodash\\lodash.js",
			"name": "lodash.js",
			"cplx": 560,
			"func": 233,
			"loc": 1994
		}]
	}]
}